sudo: required
services:
        - docker

before_install:
        - docker build -t bicefalo/docker-react:1.0 . 

script: 
        - docker run  bicefalo/docker-react:1.0  npm run test -- --coverage

